### ISSUE TITLE
Start camera with another thread

### ISSUE THREAD

**Issue by furedal** [dm77/barcodescanner#1]
Hey! Because of the delay when fetching an camera instance. Is it possible to run ZXingScannerView.startCamera on a different thread than the UI thread? That would make the switching through an activity to the camera activity look a bit smoother.

**Comment by Keshava11** [comment]
Hi
 I was facing same problem with the start time of camera.

 It was taking around 3 seconds to load camera preview. ScannerView was in a DialogFragment.

 Then instead of adding ZxingScannerView in the xml I inflated it dynamically and that too using HandlerThread that 
separtes scannerview intsantiation code for a little while and then delegates it to UI thread again. 

 I did it to first inflate the static layout and then continue to add ZxingScannerView and then start camera.

**Comment by dm77** [comment]
This is (hopefully) fixed in v1.8.4
