### ISSUE TITLE
do not automatically stopCamera after a result is found

### ISSUE THREAD

**Issue by rgl** [dm77/barcodescanner#115]
Currently, after a result is found, the camera is stopped at:

https://github.com/dm77/barcodescanner/blob/master/zxing/zxing/src/main/java/me/dm7/barcodescanner/zxing/ZXingScannerView.java#L124

Can we make this configurable? I can submit a patch if you want.

It would also be great if we could pause the scan, and leave the last captured image frame on screen, and resume the scan later. this without stopping the camera (actually, it could stop, but I don't want to see a black screen flicker that happens just after you start it again).

**Comment by pdebonte** [comment]
I, too, would like to have barcodescanner allow scanning without closing (and thus resetting) the camera device.

**Comment by divankov** [comment]
I think in 1.8.4 release notes it should be emphasized that you may want to explicitly stopCamera in handleResult yourself now. For instance you decide to show some actions dialog and no longer need camera to run or flash to keep working if it was on. And afaics also that you should probably still keep stopCamera/startCamera in activity onPause/onResume (rather than replace it with new stopCameraPreview/resumeCameraPreview).

**Comment by Draffodx** [comment]
+1 for this feature

**Comment by dm77** [comment]
Fixed in 1.8.4
