### ISSUE TITLE
Starting camera within dialog gives black screen

### ISSUE THREAD

**Issue by EnduroXPro** [dm77/barcodescanner#150]
I would like to start the camera within a dialog. 
But when I start the camera there it just gives me a black screen. 

My fragment`s code: 

 @Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);

```
    if(isVisibleToUser){
        MaterialDialog dialog = new MaterialDialog.Builder(getActivity())
                .title("QR Code scannen")
                .content("Möchtest du den QR Code scannen oder selbst eingeben?")
                .positiveText("eingeben")
                .negativeText("scannen")
                .onNegative(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        if(mScannerView!=null){
                            new Handler().post(new Runnable() {
                                @Override
                                public void run() {
                                    mScannerView.startCamera();
                                }
                            });
                        }
                    }
                })
                .show();
    } else {
        if(mScannerView!=null){
            mScannerView.stopCamera();
        }
    }
}

@Override
public void handleResult(Result rawResult) {
    Toast.makeText(getActivity(), "Contents = " + rawResult.getText() +
            ", Format = " + rawResult.getBarcodeFormat().toString(), Toast.LENGTH_SHORT).show();
    mScannerView.startCamera();
}
```

Where is my mistake?
I have also seen this related post but it did not help me: 

https://github.com/dm77/barcodescanner/issues/1

**Comment by dm77** [comment]
If you running this on Android M device, you probably have to request permission first before showing the camera.

**Comment by EnduroXPro** [comment]
But it works without asking for permission when I put the line mScannerView.startCamera() directly after onResume():

@Override
    public void onResume() {
        super.onResume();
        mScannerView.setResultHandler(this);
        mScannerView.startCamera();
    }

The code below works for me. But I need a dialog before starting camera

**Comment by Rking788** [comment]
I am also seeing this issue. More specifically the dialog that is being displayed is the one requesting permissions on Android M. When I select 'Allow' when requesting permission to the camera and then start the camera in the `onRequestPermissionsResult` callback, the camera does not start. I have to do the following to get the camera preview to turn on 

- start
- stop
-start

And after starting it the last time, auto-focus seems broken. This seems like it could also be related to Issue #122

**Comment by Rking788** [comment]
I had a chance to take a closer look at this. It seems like the CameraPreview class is not registering for the SurfaceHolder.Callback early enough. The CameraPreview doesn't register for the callback until `initCameraPreview` is called, which is a result of `startCamera`. Since we are not calling `startCamera` until the dialog is interacted with or the permissions are accepted, the library is not receiving the `surfaceCreated` callback so `this.mSurfaceCreated` is always set to false in the CameraPreview.

With that field always false, the check in the `doAutoFocus` callback is never true. This means `safeAutoFocus` is never called.

As far as i can tell, moving these two lines:

    this.getHolder().addCallback(this);
    this.getHolder().setType(3);

from `initCameraPreview` to the CameraPreview constructor will at least fix the autofocus issue. I'm not sure about the black camera preview problem yet.

**Comment by Rking788** [comment]
Deleted my last comment because i realized i was working with an older version of the library and the change i suggested has already been made.

**Comment by Zapnologica** [comment]
So do we have to do anything specific for android m devices?
