### ISSUE TITLE
Google Mobile Vision

### ISSUE THREAD

**Issue by pranaysharma** [dm77/barcodescanner#169]
Hi,
Just wanted to know if this Library has any advantages over [Google's Mobile Vision API?](https://developers.google.com/vision/)

**Comment by vbuberen** [comment]
Hi, pranaysharma,
Actually no, it hasn`t advantages over Vision API, because it has enough problems to be fixed, but it is a good alternative to orginal Zxing, cause it is easier to integrate, more lightweight and you import it using Gradle without any troubles.
But, I switched to this library from Vision API in the app which I am developing right now, because Vision has one serious problem on some devices (I have met it only on Nexus 5x, but it was enough for me to start looking for another library). And I am talking about version 8.4.0 which is the last for this moment. For more details about this problem you can look here (opened this issue yesterday): 
https://github.com/googlesamples/android-vision/issues/63
Hope it is going to be fixed soon so I could switch to it again.

**Comment by dm77** [comment]
#286 integrates this.
