### ISSUE TITLE
Aztec support

### ISSUE THREAD

**Issue by gergelyjanosi** [dm77/barcodescanner#210]
Zxing already supports AZTEC code. Would it be possible to include support into this library? Thanks in advance. Gergely Jánosi

**Comment by dm77** [comment]
So sorry for the delay :(. This should have been implemented a long while back. Will make sure to include it in the upcoming release

**Comment by suryamegham1729** [comment]
@dm77, Hi no support for Aztec codes for Zbar yet ? any plans to release near future..

**Comment by dm77** [comment]
@suryamegham1729 Don't think zbar for android supports AZTEC. Please check with project owners here https://sourceforge.net/projects/zbar/files/AndroidSDK/. I don't think you will get anything back though since that project hasn't been maintained since 2012

zxing support has been merged in #299. Will release 1.9.2 this weekend

**Comment by suryamegham1729** [comment]
Thank you very much Dushyanth...

On Fri, May 5, 2017 at 9:26 PM, Dushyanth Maguluru <notifications@github.com

**Comment by suryamegham1729** [comment]
@dm77, Hi any update on Aztec support for zxing (1.9.2) ?

**Comment by dm77** [comment]
@suryamegham1729 Sorry for the delay. Just pushed 1.9.2
