### ISSUE TITLE
ZXing Scanner Has Trouble with 1d bar codes

### ISSUE THREAD

**Issue by marksalpeter** [dm77/barcodescanner#242]
If I make a smallish scanner window and try scanning a 1d bar code, zxing seems to have a hard time recognizing it.

**Comment by dpeters-ipc** [comment]
We have the same issue with version 1.9 on a Samsung Galaxy S4 mini. 1.8.4 works.

**Comment by mdibaiee** [comment]
I am experiencing the same, it's interesting that the height of the window matters! With height: 300 it doesn't work but with 500 it works.

**Comment by mdibaiee** [comment]
Actually, if you go small enough (200px height), even QR codes will stop working.

**Comment by mdibaiee** [comment]
For anyone struggling with this issue, I found this hack which works:

```
    return ClipRect(
      child: SizedOverflowBox(
        size: Size(300, 200),
        child: ConstrainedBox(
          constraints: BoxConstraints(
            maxWidth: 300,
            maxHeight: 301
          ),
          child: PlatformAiBarcodeScannerWidget(
            platformScannerController: _scannerController,
          ),
        ),
      ),
    );
```

You can now set the size in `SizedOverflowBox` to any value you want, because the the barcode scanner will overflow from `SizedOverflowBox`, it will not be affected by the size. Then `ClipRect` cuts the extra overflowing parts out and you have a barcode scanner of your desired size.
