### ISSUE TITLE
Huawei P9 it not work

### ISSUE THREAD

**Issue by WeRockStar** [dm77/barcodescanner#287]
Exception: Camera new cameraInitNormal: 0

**Comment by vickyleu** [comment]
我这边也一样,不报异常但是什么都识别不了,努比亚的手机也是,识别率奇低,三重识别都没用,麻烦的是我们的产品是面向工厂的,工厂老板都爱用华为手机,头疼

**Comment by WeRockStar** [comment]
@vickyleu English please. :)

**Comment by dm77** [comment]
Hmm based on similar bug report here https://github.com/oney/react-native-webrtc/issues/215, tend to think it might have to do something with deprecated Camera api. 

Since I don't have a P9 device with me, would it be possible for you to make sure your app first has the camera permissions? Thank you.

**Comment by WeRockStar** [comment]
@dm77 I'm sure has granted camera permission.

**Comment by danielcerny** [comment]
@dm77 Granted, for sure. Probably deprecated Camera1 API. Camera2 API usage needed.

**Comment by WeRockStar** [comment]
Now. I fix this problem with PR #293.

**Comment by vagrant1991** [comment]
getOptimalPreviewSize method at CameraPreview , the algorithm is wrong.

**Comment by vagrant1991** [comment]
@dm77  width 1080 height 1572  huawei p9,  the result is 144 * 208

**Comment by vagrant1991** [comment]
change the if statement        

  if (Math.abs(size.height - targetHeight) < minDiff && size.height >= 480) {
                optimalSize = size;
                minDiff = Math.abs(size.height - targetHeight);
  }

now is ok,   point is size.height >= 480

**Comment by dm77** [comment]
Thanks @vagrant1991

**Comment by dm77** [comment]
@vagrant1991 @WeRockStar You both had different solutions for the problem. @WeRockStar - you had somebody verify your commit (#293) and so I went with a slight variation of yours for now. 

I didn't want to hardcode the aspect tolerance to 0.5 like you did, but wanted it to be customizable. For example take a look at the setAspectTolerance call in this example: https://github.com/dm77/barcodescanner/blob/master/zxing-sample/src/main/java/me/dm7/barcodescanner/zxing/sample/ScalingScannerActivity.java#L35

Note that this is just a temporary fix. I still don't have a good grasp of what the issue is. My questions to any of you experiencing issues on Huawei devices:

1.) Do you always see this error: "Exception: Camera new cameraInitNormal: 0" ?
2.) Are you able to replicate the error with zxing-sample app?
3.) If you don't see an exception, what do you guys mean when you say "it won't work"? Is the screen blank or is the viewfinderview too small?

**Comment by WeRockStar** [comment]
@dm77 I agree with you. Don't should hardcode the aspect tolerance. But my commit #293 just workaround solution for me. Thanks for support the problem.

Regards

**Comment by anastaciakv** [comment]
@dm77  You saved my day! Thank you very much for the aspect tolerance!

**Comment by sg552** [comment]
thanks, solved my problem about HUAWEI P10.

**Comment by vagrant1991** [comment]
@WeRockStar  @dm77  @vickyleu  @danielcerny @aegamesi @sg552  The point is not ASPECT_TOLERANCE size,  the point is getOptimalPreviewSize method can't achieve the desired result on different devices. maybe huawei p9 p8 p10 p... other device.....

There is no exception, I can reproduce always, "it won't work" mean the  viewfinderview is blurred, because onPreviewFrame method at ZXingScannerView can't get the right camera size. It's irrelevant to Camera API (Camera vs Camera2)

change the method to : 

    private Camera.Size getOptimalPreviewSize() {
        if (mCameraWrapper == null) {
            return null;
        }
        List<Camera.Size> sizes = mCameraWrapper.mCamera.getParameters().getSupportedPreviewSizes();
        int w = getWidth();
        int h = getHeight();
        if (DisplayUtils.getScreenOrientation(getContext()) == Configuration.ORIENTATION_PORTRAIT) {
            int portraitWidth = h;
            h = w;
            w = portraitWidth;
        }

        if (sizes == null) return null;

        Camera.Size optimalSize = null;
        double minDiff = Double.MAX_VALUE;

        int targetHeight = h;
        Collections.sort(sizes, new Comparator<Camera.Size>() {
            @Override
            public int compare(Camera.Size lhs, Camera.Size rhs) {
                return lhs.height - rhs.height;
            }
        });

        int orientation = DisplayUtils.getScreenOrientation(getContext());
        int width;
        int height;
        if(mSquareViewFinder) {
            if(orientation != Configuration.ORIENTATION_PORTRAIT) {
                height = (int) (getHeight() * DEFAULT_SQUARE_DIMENSION_RATIO);
                width = height;
            } else {
                width = (int) (getWidth() * DEFAULT_SQUARE_DIMENSION_RATIO);
                height = width;
            }
        } else {
            if(orientation != Configuration.ORIENTATION_PORTRAIT) {
                height = (int) (getHeight() * LANDSCAPE_HEIGHT_RATIO);
                width = (int) (LANDSCAPE_WIDTH_HEIGHT_RATIO * height);
            } else {
                width = (int) (getWidth() * PORTRAIT_WIDTH_RATIO);
                height = (int) (PORTRAIT_WIDTH_HEIGHT_RATIO * width);
            }
        }

        if(width > getWidth()) {
            width = getWidth() - MIN_DIMENSION_DIFF;
        }
        if(height > getHeight()) {
            height = getHeight() - MIN_DIMENSION_DIFF;
        }

        for (Camera.Size size : sizes) {
            if (size.height > height && size.width > width) {
                optimalSize = size;
                break;
            }
        }

        if (optimalSize == null) {
            minDiff = Double.MAX_VALUE;
            for (Camera.Size size : sizes) {
                if (Math.abs(size.height - targetHeight) < minDiff) {
                    optimalSize = size;
                    minDiff = Math.abs(size.height - targetHeight);
                }
            }
        }
        return optimalSize;
    }


Now , all devices are ok. Try to get the first camera size which is larger than the size of viewfinderview

**Comment by stephenruda** [comment]
@dm77 @vagrant1991 
The getOptimalPreviewSize() method proposed by vagrant1991 has worked perfectly for me.

I was having poor results with v1.9.8.  Swapping in the method above solved the problems I was having.

Here were the issues I was having...

1. Setting the ASPECT_TOLERANCE is not a feasible solution for me.  For example, the barcodes scan normally on some devices with the default aspect tolerance but need aspect tolerance 0.5f in order to work correctly on other devices (the HUAWEI problem).  My Galaxy S4 with front facing camera would only work with the tolerance set to 0.5f.  I can't carve out a giant IF statement in my code that goes through all of the known devices that need to be set to 0.5f.
2. I previously used v1.8.2 of the library.  On all of my devices, the scanning worked just fine.  On the v1.9.8, I am not getting successful scans when the barcode is very clearly in the scan region.  On my Galaxy S7, I would place the barcode perfectly in the scan region and nothing would happen.  I would need to hold it much further back or even adjust it a little above the scan region for it to scan successfully.  Something was clearly off.

The above method solved these problems and it scans as I would expect.  It is also much more helpful that you don't have to specify an ASPECT_TOLERANCE.  In my opinion, this should be the method used for getOptimalPreviewSize() rather than what is currently used in v1.9.8.

Hopefully others can come forward and discuss their results with this method.

ALSO, if anyone is wondering the values of the constants (such as LANDSCAPE_WIDTH_HEIGHT_RATIO) they are found in the ViewFinderView.java file.

I'd be happy to put together a pull-request @dm77 if you are interested.

Thanks!

**Comment by geetves** [comment]
+1 for pull request mentioned by **stephenruda**

**Comment by danielggg33** [comment]
Hi guys,
I have tested the  zxing-sample app on Huawei Mate 9 7.0, P9 and P9 Lite 6.0 , and the problems related to the blurred scan preview  and difficulties to scan absolutely don't happen.
However, I tried to implement  v1.9.8 following the instructions described in the readme file and yes, it happened to me too, totally blurred on every Huawei I tried.

In my case I discovered that the problem was related to the action bar. If you check the sample app it have set <item name="windowActionBar">false</item> and its own toolbar implementation in the code. But when I tried, I did it without those two aspects.

What I did to workaround this issue is to set in the manifest file the following style to my activity:
<style name="AppOverlayTheme" parent="@style/Theme.AppCompat.Light">
   <item name="windowActionBarOverlay">true</item>
</style>

I hope this can help you, please let me know if you have any problem.

**Comment by HarshaKanchina** [comment]
Hi @vagrant1991

When I try to replace the method with yours 'getOptimalPreviewSize', I'm getting the following as unresolved symbols:

mSquareViewFinder
DEFAULT_SQUARE_DIMENSION_RATIO
LANDSCAPE_HEIGHT_RATIO
LANDSCAPE_WIDTH_HEIGHT_RATIO
PORTRAIT_WIDTH_RATIO
PORTRAIT_WIDTH_HEIGHT_RATIO
MIN_DIMENSION_DIFF

Can you please help? I'm kind of new to all this.

Or, if you have an aar/jar with the above method already replaced, can you please share it? We're running into an issue for specific devices. Didn't expect this to happen, so need a solution.  Thanks.
