### ISSUE TITLE
Scanner does not work in portrairt mode

### ISSUE THREAD

**Issue by Cyborg101** [dm77/barcodescanner#336]
First of all thanks for this amazing library, really made my android developer life easier :)
I have some problem with the last version of the app (1.9.5). I basically copied and pasted the SampleScanner example provided and the scanner works fine only in landscape mode, while in portrait mode the result handler is not even called. I have a galaxy s5 mini with Android 6.0 installed. Notice that I do not have the same problem if the dependency I add to gradle is 1.9.4.

**Comment by Komoi** [comment]
That happens on my side too, exactly as you described.
Android Studio 3 canary, OnePlus3T on 7.1.1

**Comment by dm77** [comment]
How annoying. The fix in 1.9.5 was supposed to resolve issues on Nexus 5x. Can you guys test the attached sample APK on your devices and see if you can still replicate the issue? Thank you so much for the help. 

https://www.dropbox.com/s/v63vlzwsb4tl5ph/zxing-sample-debug.apk?dl=0

**Comment by Komoi** [comment]
Hi, tested your APK, still same bug on portrait when using SimpleActivity.Regards, OndrejOn 2 Aug 2017 02:53, Dushyanth Maguluru <notifications@github.com> wrote:How annoying. The fix in 1.9.5 was supposed to resolve issues on Nexus 5x. Can you guys test the attached sample APK on your devices and see if you can still replicate the issue? Thank you so much for the help.
https://www.dropbox.com/s/v63vlzwsb4tl5ph/zxing-sample-debug.apk?dl=0

**Comment by dm77** [comment]
Thank you

**Comment by dm77** [comment]
I just went and bought a Samsung Galaxy Sol device hoping that I can replicate the bug, but unfortunately everything works fine.

**Comment by Komoi** [comment]
I tried that on 1.9.3 and it worked without described problem. I will be able to test it more later today.On 2 Aug 2017 05:36, Dushyanth Maguluru <notifications@github.com> wrote:I just went and bought a Samsung Galaxy Sol device hoping that I can replicate the bug, but unfortunately everything works fine.

**Comment by dm77** [comment]
Thank you @Cyborg101 @Komoi for the feedback. I am going to revert the Nexus 5x fix for now and release 1.9.6 shortly.

**Comment by Cyborg101** [comment]
Thanks for the help @dm77, quite ironic that the two devices we use to debug at work are nexus 5x and a samsung galaxy s5 mini 👍

**Comment by dm77** [comment]
@Cyborg101 Since you have both the problem devices, would you please test the attached APK file for me? That would be very helpful. I feel like the attached APK should fix portrait scanning on both devices. Really appreciate your help. https://www.dropbox.com/s/v63vlzwsb4tl5ph/zxing-sample-debug.apk?dl=0

**Comment by Komoi** [comment]
SimpleActivity scans in both orientations and very quickly in latest APK.On 2 Aug 2017 23:40, Dushyanth Maguluru <notifications@github.com> wrote:@Cyborg101 Since you have both the problem devices, would you please test the attached APK file for me? That would be very helpful. I feel like the attached APK should fix portrait scanning on both devices. Really appreciate your help. https://www.dropbox.com/s/v63vlzwsb4tl5ph/zxing-sample-debug.apk?dl=0

**Comment by dm77** [comment]
Thank you @Komoi

**Comment by Cyborg101** [comment]
@dm77 I will try it tomorrow with the galaxy mini and will let you know

**Comment by Cyborg101** [comment]
@dm77 Works in both orientations with galaxy s5 mini! Thanks again for your help!

**Comment by dm77** [comment]
Yay! Thanks for confirming @Cyborg101

**Comment by Destiner** [comment]
Hmm. Looks like I am in minority here, but I couldn't get it worked on 1.9.7. I tried really hard, because I didn't know about the problem in previous versions. I tried 1.9.3 and it works instantly every time.
Running Nexus 5X with Android 7.1.2 (API 25).
It also works on 1.9.4 and fails on 1.9.5 and 1.9.6 :/

**Comment by androidovshchik** [comment]
i have noticed that autofocus bad works in portrait mode
although landscape works fine
