### ISSUE TITLE
Issue with Multi-Barcode shoot . 

### ISSUE THREAD

**Issue by ahmedeltaher** [dm77/barcodescanner#350]
for ZBarScannerView when you try to scan a specific barcode from more than one , the scanner will always take the first barcode pattern , not the right one which inside the view finder rectangle . 
according to the below screenshot , the result will be `5051890268112`

Android Version `7.1.2`
Build Number `1.9.4`
Device Module `Nexus 5x`

![7211062277811958881-account_id 4](https://user-images.githubusercontent.com/1812129/29273172-7ce1fa3e-8103-11e7-9410-9315e73f68ab.png)

**Comment by dm77** [comment]
This was fixed in the latest version 1.9.7

**Comment by ahmedeltaher** [comment]
not fixed in 1.9.7 cause scan it self doesn't work in android 1.9.7 in 
Android Version `7.1.2`
Device Module `Nexus 5x`

**Comment by dm77** [comment]
Hi @ahmedeltaher, what I was referring to was that there was a bug with zbar library, where qrcodes outside the viewfinder were being scanned. That is no longer the case now with 1.9.7. 

The issue with Nexus 5x is just a general portrait scanning problem due to the weird camera orientation on that device. I am discussing with @yuriy-budiyev in #346 to see if he can submit a pull request. I don't have a Nexus5x device myself so it is a little hard for me to provide a fix.

**Comment by dm77** [comment]
Hi @ahmedeltaher . I think I finally fixed the Nexus 5x scanning issue in v1.9.8. Can you please confirm when you get a chance? Thank you so much.
