### ISSUE TITLE
How to change `scanner` borders size

### ISSUE THREAD

**Issue by abol3z** [dm77/barcodescanner#49]
I want to increase the size of the scanning area in the scanner view, how can I do this?
Thanks

**Comment by engmonsh** [comment]
and Also how to change the border color of the scanning area?

**Comment by kalvish21** [comment]
You have to extend this class:

https://github.com/dm77/barcodescanner/blob/master/core/src/main/java/me/dm7/barcodescanner/core/ViewFinderView.java

And then modify override some of the methods in it. The method `public void drawViewFinderBorder` is probably what you're looking for.

**Comment by engmonsh** [comment]
Thank you very much :+1:

**Comment by deepdoradla** [comment]
Can anyone please explain how do I add color or change the border size. I am new to android programming hence struggling. I have added this library via gradle. The problem is in the lib folder I can only see 
public void drawLaser(android.graphics.Canvas canvas) { /* compiled code */ }.

Now I don't know how I should call the method in to my scanActivity. If I have to use the code from the above link and then change the color or edit the size I don't know how I shud extend that class. I tried extending it but I don't think I am dong it right. Please help guys.

**Comment by dm77** [comment]
#80 might help

**Comment by dm77** [comment]
Thanks to @marchelo , his pull request has been now merged in. Changes available in version 1.8

**Comment by dycasxe101** [comment]
can anyone explain how to resize rectangle of scanner, honestly iam so confuse

**Comment by marchelo** [comment]
Hey, @dycasxe101 
try next thing:
```
    @Override
    public void onCreate(Bundle state) {
        super.onCreate(state); 
        mScannerView = new ZXingScannerView(this) {
            @Override
            protected IViewFinder createViewFinderView(Context context) {
                return new CustomViewFinderView(context);
            }
        };
        setContentView(mScannerView);
    }
    ...
    private static class CustomViewFinderView extends ViewFinderView {
        ...
        @Override
        public Rect getFramingRect() {
            Rect originalRect = super.getFramingRect();
            return new Rect(originalRect.left + 20, originalRect.top + 20, originalRect.right - 20, originalRect.bottom - 20);
        }
    }
```

in theory this should reduce size of rect by 20 pixels from each side.
But NOTE: such approach is not optimal, it's more like a hack and please do not make complex computations in "getFramingRect()" method.

**Comment by dycasxe101** [comment]
@marchelo thanks for response. Alhamdulillah yesterday, its was done
