### ISSUE TITLE
Issue with camera view ratio in version 1.7

### ISSUE THREAD

**Issue by ultraon** [dm77/barcodescanner#84]
Hi all.
After updating 1.6.3 to 1.7 i have issue with camera view ratio. There is black borders. Could you add option for changes made in version 1.7. I need to have camera view behavior such as in version 1.6.3 with stretching camera view. Please.

**Comment by dm77** [comment]
Hi @ultraon - The appearance of black borders indicates that the preview size of your camera is unable to occupy the entire screen. That is probably because you have surrounding views which are reducing the preview size. For best results use the app full screen theme and make sure any other view elements are overlaid on top of the camera preview.

The problem with stretching is that it causes the QR Scanning to work incorrectly or in some cases to not even recognize the barcode. 

See the samples to see how you can use the full screen theme or overlay elements.

Thanks!
