### ISSUE TITLE
Scanner View has black bars on both sides

### ISSUE THREAD

**Issue by fadils** [dm77/barcodescanner#87]
![screenshot_2015-05-26-07-48-50](https://cloud.githubusercontent.com/assets/6204776/7803721/af9a82a0-0380-11e5-9d40-cdd9bcca771c.png)

Sony Experia C2005.
Android 4.3

**Comment by markus-woerz** [comment]
I can confirm the same behaviour on my device:

    Sony Xperia Z3 Compact
    Android 5.0.2
    me.dm7.barcodescanner:zxing:1.7.1

**Comment by dm77** [comment]
Hi @fadils @markus-woerz - This is because the action bar in your view is taking up part of the available view size. If we stretched the camera preview it would result in issue like #8 and would cause QR scanning to not work correctly. So the solution for this problem is to use an overlay action bar and overlay other elements as you need. For example see the XML layout I provided in this issue #67

**Comment by dm77** [comment]
Oh and also a full screen theme needs to be applied like mentioned in #67 . Sorry that this isn't obvious from the README. I will update it as soon as I can.

**Comment by shubhamsizzles** [comment]
@dm77 One way that this could be solved is to feed proper data to the recognition engine, and only stretch the preview that user sees to fill full width. Could anyone tell me which line is this preview is coming from? Also, if the problem is specific to QR codes, could it be possible to stretch in case of barcodes only? The black bars are very distracting, specially in smaller fragments.

**Comment by chenupt** [comment]
I have the same problem. Using a full screen theme can fix it. But, I have to place a ToolBar in my activity. There is a method [adjustViewSize](https://github.com/dm77/barcodescanner/blob/5efbf424d8012ca53c0d1cdcdff14e25ae40a010/core/src/main/java/me/dm7/barcodescanner/core/CameraPreview.java#L125) I found in CameraPreview. It is the reason of the black bar which make the view size equals to camera preview size. If I delete it, preview full screen just a little out of shape. I think it is accepted. So how about add some attributes that toggle adjustViewSize?

**Comment by ThinWonton** [comment]
@chenupt 
did you solve?
the same problem i meet.
waitting for an answer.

**Comment by chenupt** [comment]
@ThinWonton checkout the source and remove [adjustViewSize](https://github.com/dm77/barcodescanner/blob/5efbf424d8012ca53c0d1cdcdff14e25ae40a010/core/src/main/java/me/dm7/barcodescanner/core/CameraPreview.java#L125) .
