### ISSUE TITLE
Barcodes ignored after toggling camera facing 'fast' with stopCamera and startCamera(int)

### ISSUE THREAD

**Issue by FizzyMobile** [dm77/barcodescanner#93]
The problem occurs when _startCamera(int)_ (with different camera id than is currently running) is called right after _stopCamera()_. The preview is ok, there is no problem with camera, yet the scanner callback is not called. Scanning works good after changing back camera facing, or changing device orientation.

**To reproduce:**
_me.dm7.barcodescanner.zxing.sample.ScannerFragment.java_ (lines 118,119)

``` java
    onCameraSelected(mCameraId == 0 ? 1 : 0);
    // DialogFragment cFragment = CameraSelectorDialogFragment.newInstance(this, mCameraId);
    // cFragment.show(getActivity().getSupportFragmentManager(), "camera_selector");
```

This issue occurs on:
- Lenovo A7600-H, Android 4.2.2
- Samsung Tab 2 GT-P5110, Android 4.2.2

This issue does **not** occur on:
- Nexus 5, Android 5.1.1
- Samsung Galaxy S II GT-I9100, Android 4.1.2

**Comment by dm77** [comment]
Wish I had those devices to test. Will see if I can replicate

**Comment by murilopapa** [comment]
same problem here! the preview works fine, but the callback is never called by the 2º camera
startCamera(0) - everything working
stopCamera()
startCamera(1) - everything works, less the callback 
stopCamera()
startCamera(0) - everything working again

the problem is when we switch cameras, the callback just works with the first camera started
